name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Install unzip
        run: sudo apt-get install -y unzip
      
      - name: Download and Install SonarQube Scanner
        run: |
          SCANNER_VERSION="4.8.0.2856"  # Update this to the desired version
          SCANNER_DIR="sonar-scanner-cli-$SCANNER_VERSION-linux"
          curl -L "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/$SCANNER_VERSION/$SCANNER_DIR.zip" -o sonar-scanner.zip

          # Check if the download was successful
          if [ $? -ne 0 ]; then
            echo "Failed to download SonarQube Scanner."
            exit 1
          fi

          # Verify the downloaded file exists and is not empty
          if [ ! -s sonar-scanner.zip ]; then
            echo "Downloaded file is empty or does not exist."
            exit 1
          fi

          # Unzip the downloaded file
          unzip sonar-scanner.zip

          # Check if unzip was successful
          if [ $? -ne 0 ]; then
            echo "Failed to unzip SonarQube Scanner."
            exit 1
          fi

          # Move the scanner to a proper directory and add to PATH
          sudo mv $SCANNER_DIR /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=order-lifecycle \
          -Dsonar.sources=./ \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
