name: testing workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - name: Echo something
        run: echo "output message!!"

      - name: Print another command
        run: echo "goodbye bitches!!"