name: testing workflow

on:
  push:
    branches:
      - main 
  pull_request:
    types:
      - opened
    branches:
      - main     

jobs:
  theme:
    runs-on: ubuntu-latest

    steps:
      - name: Echo something
        run: echo "output message!!"

      - name: Print another command
        run: echo "goodbye bitches!!"
  
  test:
    needs: theme
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
        
      - name: Installing dependencies
        run: pip install -r requirements.txt
      
      - name: Running Unit Testing
        run: pytest tests/test.py
    
  deploy: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying de code
        run: echo "Code is deploying"
        